export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    c:"C",
    c_plus_plus: "C++",
    mongo: "MongoDB",
    mysql: "MySQL",
    html: "HTML",
    css: "CSS",
    ejs: "EJS",
    node: "Node.js",
    vscode: "VSCode",
    figma: "Figma",
    git: "Git & GitHub",
    react: "React",
    express: "Express",
    vue:"Vue",
    linux:"Linux",
    numpy:"Numpy",
    pandas:"Pandas",
    matplotlib:"Matplotlib",
    scikit_learn:"Scikit-learn",
    pytorch:"PyTorch",
    huggingface:"HuggingFace",
    vim:"Vim",
    nano:"Nano",
    socket:"Socket.io",
    prisma:"Prisma",
    docker:"Docker",
    gradio:"Gradio",
    sql:"SQL"
}